name: simple_app
description: "An awesome flutter app generate by mason"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  dio: ^5.6.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.3
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.6
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  custom_lint: ^0.6.5
  http_mock_adapter: ^0.6.1
  logger: ^2.4.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
