name: simple_app
description: "this is a simple app with go router"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  simple_ui:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  custom_lint: ^0.6.7
  http_mock_adapter: ^0.6.1
  logger: ^2.4.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true