name: exemple 
packages:
  - app/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .

  analyze:custom_lint:
    run: melos exec -- dart run custom_lint
    description: Run `dart custom_lint ` in all packages.

  remove_unused_import:
    run: melos exec -- dart fix --apply --code=unused_import
    description: remove unused import in all file.

  watch_runner:
    run: melos exec --depends-on="build_runner" -- "dart run build_runner watch -d"
    description: Watch all generated files for Dart & Flutter packages in this project.

  build_runner:
    run: melos exec --depends-on="build_runner" -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.

  spider:
    run: melos exec --depends-on="spider" -- spider build
    description: Run spider to generate resources.

  all:
    run: |
      melos clean
      melos bs
      melos watch_runner
      melos build_runner

command:
  bootstrap:
    environment:
      sdk: ">=3.3.1 <4.0.0"
      flutter: ">=3.3.1 <4.0.0"
